# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7ffa3de8b166eeb591aef78be0f41f933e2d54add3f00b9f4f1c0fd3d85147e02e96d5295be3a6c8ae894ec5d3fb03db1a213df608ebbc410a18a7c122780a

test:
  secret_key_base: 93646c4460fc5ebfb591c4db5f001110c149ef3e184546aa56b3f3c0efe12197e8922e42d8254de21f08ee156b89f5fa9e27330dba30c5406412ed758eda486c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
